name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: go.mod
          # setup-go v4 uses cache automatically, which conflicts with golangci-lint's cache.
          # See https://github.com/golangci/golangci-lint-action/pull/704
          cache: false
      # A workspace file is needed for golangci-lint to check the sub-modules.
      # https://github.com/golangci/golangci-lint-action/issues/544
      - run: make go-workspace
      # To check sub-modules, you need to supply their paths as positional arguments.
      # This step finds the paths and adds them to a variable which is used
      # later in the args value.
      # https://github.com/golangci/golangci-lint/issues/828
      - name: find-go-modules
        id: find-go-modules
        run: |
          find . -type f -name 'go.mod' -printf '%h/...\n' \
          | jq -r -R -s 'split("\n")[:-1] | sort | join(" ") | "GO_MODULES=\(.)"' \
          >> "$GITHUB_OUTPUT"
      - uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: v1.55.2
          args: --timeout=30m --config=.golangci.ci.yaml ${{ steps.find-go-modules.outputs.GO_MODULES }}
